[출처](https://www.youtube.com/watch?v=lG8pEwvYwCw&list=PL7ZVZgsnLwEEZcVusN-fV_sJhQHq833OS&index=2)

# Pandas 한번에 제대로 배우기

![image.png]()



---

In [1]:
import pandas as pd
import numpy as np

## Pandas 객체

### Series 객체

In [2]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0])
s

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64

In [3]:
s.values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [4]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [5]:
s[1]

0.25

In [6]:
s[1:4]

1    0.25
2    0.50
3    0.75
dtype: float64

In [7]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0],
              index=['a','b','c','d','e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [8]:
s['c']

0.5

In [9]:
s[['c','d','e']]

c    0.50
d    0.75
e    1.00
dtype: float64

In [10]:
'b' in s.index

True

In [11]:
'b' in s

True

In [12]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0],
              index=[2, 4, 6, 8, 10])
s

2     0.00
4     0.25
6     0.50
8     0.75
10    1.00
dtype: float64

In [13]:
s[2:]

6     0.50
8     0.75
10    1.00
dtype: float64

In [14]:
s.unique()

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
s.value_counts()

1.00    1
0.75    1
0.50    1
0.25    1
0.00    1
dtype: int64

In [16]:
s.isin([0.25, 0.75])

2     False
4      True
6     False
8      True
10    False
dtype: bool

In [17]:
pop_tuple = {'서울특별시': 9720846,
             '부산광역시': 3404423,
             '인천광역시': 2947217,
             '대구광역시': 2427954,
             '대전광역시': 1471040,
             '광주광역시': 1455048}

population = pd.Series(pop_tuple)
population

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
광주광역시    1455048
dtype: int64

In [18]:
population['서울특별시']

9720846

In [19]:
population['서울특별시':'인천광역시']

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
dtype: int64

### DataFrame 객체

In [20]:
pd.DataFrame([{'A':2, 'B':4, 'D':3},{'A':4, 'B':5, 'C':7}]) # NaN Not a number

   A  B    D    C
0  2  4  3.0  NaN
1  4  5  NaN  7.0

In [21]:
pd.DataFrame(np.random.rand(5, 5), 
             columns=['A','B','C','D','E'],
             index=[1, 2, 3, 4, 5] )

          A         B         C         D         E
1  0.985089  0.650508  0.295377  0.730583  0.454024
2  0.141221  0.336198  0.732748  0.740686  0.213304
3  0.296957  0.596656  0.066812  0.960665  0.325695
4  0.900780  0.943593  0.303575  0.473061  0.983769
5  0.873801  0.546442  0.238265  0.699356  0.210712

In [22]:
male_tuple = {'서울특별시': 4732275,
              '부산광역시': 1668618,
              '인천광역시': 1476813,
              '대구광역시': 1198815,
              '대전광역시': 734441,
              '광주광역시': 720060}
 
male = pd.Series(male_tuple)
male

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
dtype: int64

In [23]:
female_tuple = {'서울특별시': 4988571,
                '부산광역시': 1735805,
                '인천광역시': 1470404,
                '대구광역시': 1229139,
                '대전광역시': 736599,
                '광주광역시': 734988}

female = pd.Series(female_tuple)
female

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
dtype: int64

In [24]:
korea_df = pd.DataFrame({'인구수': population,
                         '남자인구수':male,
                         '여자인구수':female })
korea_df

           인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [25]:
korea_df.index

Index(['서울특별시', '부산광역시', '인천광역시', '대구광역시', '대전광역시', '광주광역시'], dtype='object')

In [26]:
korea_df.columns

Index(['인구수', '남자인구수', '여자인구수'], dtype='object')

In [27]:
korea_df['여자인구수']

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [28]:
korea_df['서울특별시':'인천광역시']

           인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404

### Index 객체

![image.png]()

In [29]:
idx = pd.Index([2, 4, 6, 8, 10])
idx

Int64Index([2, 4, 6, 8, 10], dtype='int64')

In [30]:
idx[1]

4

In [31]:
idx[1:2:2]

Int64Index([4], dtype='int64')

In [32]:
idx[-1::]

Int64Index([10], dtype='int64')

In [33]:
idx[::2]

Int64Index([2, 6, 10], dtype='int64')

In [34]:
print(idx)
print(idx.size)
print(idx.shape)
print(idx.ndim)
print(idx.dtype)

Int64Index([2, 4, 6, 8, 10], dtype='int64')
5
(5,)
1
int64

#### Index 연산

![image.png]()

In [35]:
idx1 = pd.Index([1,2,4,6,8])
idx2 = pd.Index([2,4,5,6,7])
print(idx1.append(idx2))
print()
print(idx1.difference(idx2))
print()
print(idx1 - idx2) # 위에 강의 오타~ 그냥 -는 빼준다
print(idx1.intersection(idx2))
print(idx1 & idx2)
print(idx1.union(idx2))
print(idx1 | idx2)
print(idx1.delete(0))
print(idx1.drop(1))
print(idx1 ^ idx2) # 여집합

Int64Index([1, 2, 4, 6, 8, 2, 4, 5, 6, 7], dtype='int64')

Int64Index([1, 8], dtype='int64')

Int64Index([-1, -2, -1, 0, 1], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([1, 5, 7, 8], dtype='int64')



---

## 인덱싱(Indexing)

In [36]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0],
              index=['a', 'b', 'c', 'd', 'e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [37]:
s['b']

0.25

In [38]:
'b' in s

True

In [39]:
s.keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [40]:
s.items()

In [41]:
list(s.items())

[('a', 0.0), ('b', 0.25), ('c', 0.5), ('d', 0.75), ('e', 1.0)]

In [42]:
s['f'] = 1.25
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
f    1.25
dtype: float64

In [43]:
s['a':'d']

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [44]:
s[0:4]

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [45]:
s[(s >0.4) & (s < 0.8)]

c    0.50
d    0.75
dtype: float64

In [46]:
s[['a', 'c', 'e']]

a    0.0
c    0.5
e    1.0
dtype: float64

### Series 인덱싱

In [47]:
s = pd.Series(['a', 'b', 'c', 'd', 'e'],
              index=[1, 3, 5, 7, 9])
s

1    a
3    b
5    c
7    d
9    e
dtype: object

In [48]:
s[1]

'a'

In [49]:
s[2:4]

5    c
7    d
dtype: object

In [50]:
s.iloc[1]

'b'

In [51]:
s.iloc[2:4]

5    c
7    d
dtype: object

In [52]:
s.reindex(range(10))

0    NaN
1      a
2    NaN
3      b
4    NaN
5      c
6    NaN
7      d
8    NaN
9      e
dtype: object

In [53]:
s.reindex(range(10), method='bfill')

0    a
1    a
2    b
3    b
4    c
5    c
6    d
7    d
8    e
9    e
dtype: object

### DataFrame 인덱싱

![image.png]()

In [54]:
korea_df

           인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [55]:
korea_df['남자인구수']

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [56]:
korea_df.남자인구수

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [57]:
korea_df.여자인구수

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [58]:
korea_df['남여비율'] = (korea_df['남자인구수'] * 100 / korea_df['여자인구수'])

In [59]:
korea_df.남여비율

서울특별시     94.862336
부산광역시     96.129346
인천광역시    100.435867
대구광역시     97.532907
대전광역시     99.707032
광주광역시     97.968946
Name: 남여비율, dtype: float64

In [60]:
korea_df.values

array([[9.72084600e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01],
       [3.40442300e+06, 1.66861800e+06, 1.73580500e+06, 9.61293463e+01],
       [2.94721700e+06, 1.47681300e+06, 1.47040400e+06, 1.00435867e+02],
       [2.42795400e+06, 1.19881500e+06, 1.22913900e+06, 9.75329072e+01],
       [1.47104000e+06, 7.34441000e+05, 7.36599000e+05, 9.97070319e+01],
       [1.45504800e+06, 7.20060000e+05, 7.34988000e+05, 9.79689464e+01]])

In [61]:
korea_df.T

              서울특별시         부산광역시  ...         대전광역시         광주광역시
인구수    9.720846e+06  3.404423e+06  ...  1.471040e+06  1.455048e+06
남자인구수  4.732275e+06  1.668618e+06  ...  7.344410e+05  7.200600e+05
여자인구수  4.988571e+06  1.735805e+06  ...  7.365990e+05  7.349880e+05
남여비율   9.486234e+01  9.612935e+01  ...  9.970703e+01  9.796895e+01

[4 rows x 6 columns]

In [62]:
korea_df.values[0]

array([9.72084600e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01])

In [63]:
korea_df['인구수']

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
광주광역시    1455048
Name: 인구수, dtype: int64

In [64]:
korea_df.loc[:'인천광역시', :'남자인구수']

           인구수    남자인구수
서울특별시  9720846  4732275
부산광역시  3404423  1668618
인천광역시  2947217  1476813

In [65]:
korea_df.loc[(korea_df.여자인구수 > 1000000)]

           인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2427954  1198815  1229139   97.532907

In [66]:
korea_df.loc[(korea_df.인구수 < 2000000 )]

           인구수   남자인구수   여자인구수       남여비율
대전광역시  1471040  734441  736599  99.707032
광주광역시  1455048  720060  734988  97.968946

In [67]:
korea_df.loc[(korea_df.남여비율 > 100)]

           인구수    남자인구수    여자인구수        남여비율
인천광역시  2947217  1476813  1470404  100.435867

In [68]:
korea_df.loc[ (korea_df.인구수 > 2500000) & (korea_df.남여비율 > 100)]

           인구수    남자인구수    여자인구수        남여비율
인천광역시  2947217  1476813  1470404  100.435867

In [69]:
korea_df.iloc[:3, :2]

           인구수    남자인구수
서울특별시  9720846  4732275
부산광역시  3404423  1668618
인천광역시  2947217  1476813

### 다중 인덱싱(Multi Indexing)

* 1차원의 Series와 2차원의 DataFrame 객체를 넘어 3차원, 4차원 이상의 고차원 데이터 처리
* 단일 인덱스 내에 여러 인덱스를 포함하는 다중 인덱싱

#### 다중 인덱스 Series

In [70]:
korea_df

           인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2427954  1198815  1229139   97.532907
대전광역시  1471040   734441   736599   99.707032
광주광역시  1455048   720060   734988   97.968946

In [71]:
idx_tuples = [('서울특별시', 2010), ('서울특별시', 2020),
               ('부산광역시', 2010), ('부산광역시', 2020),
               ('인천광역시', 2010), ('인천광역시', 2020),
               ('대구광역시', 2010), ('대구광역시', 2020),
               ('대전광역시', 2010), ('대전광역시', 2020),
               ('광주광역시', 2010), ('광주광역시', 2020)]
idx_tuples

[('서울특별시', 2010),
 ('서울특별시', 2020),
 ('부산광역시', 2010),
 ('부산광역시', 2020),
 ('인천광역시', 2010),
 ('인천광역시', 2020),
 ('대구광역시', 2010),
 ('대구광역시', 2020),
 ('대전광역시', 2010),
 ('대전광역시', 2020),
 ('광주광역시', 2010),
 ('광주광역시', 2020)]

In [72]:
pop_tuples = [10312545, 9728046,
              2567910, 3434423,
              2758296, 2947217,
              2511676, 2427954,
              1503664, 1471040,
              1454634, 1455048]

population = pd.Series(pop_tuples, index=idx_tuples)
population

(서울특별시, 2010)    10312545
(서울특별시, 2020)     9728046
(부산광역시, 2010)     2567910
(부산광역시, 2020)     3434423
(인천광역시, 2010)     2758296
(인천광역시, 2020)     2947217
(대구광역시, 2010)     2511676
(대구광역시, 2020)     2427954
(대전광역시, 2010)     1503664
(대전광역시, 2020)     1471040
(광주광역시, 2010)     1454634
(광주광역시, 2020)     1455048
dtype: int64

In [73]:
midx = pd.MultiIndex.from_tuples(idx_tuples)
midx

MultiIndex([('서울특별시', 2010),
            ('서울특별시', 2020),
            ('부산광역시', 2010),
            ('부산광역시', 2020),
            ('인천광역시', 2010),
            ('인천광역시', 2020),
            ('대구광역시', 2010),
            ('대구광역시', 2020),
            ('대전광역시', 2010),
            ('대전광역시', 2020),
            ('광주광역시', 2010),
            ('광주광역시', 2020)],
           )

In [74]:
population = population.reindex(midx)
population

서울특별시  2010    10312545
       2020     9728046
부산광역시  2010     2567910
       2020     3434423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454634
       2020     1455048
dtype: int64

In [75]:
population[:, 2010]

서울특별시    10312545
부산광역시     2567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454634
dtype: int64

In [76]:
population['대전광역시', :]

2010    1503664
2020    1471040
dtype: int64

In [77]:
korea_mdf = population.unstack() # 멀티 인덱스를 풀려고
korea_mdf

           2010     2020
광주광역시   1454634  1455048
대구광역시   2511676  2427954
대전광역시   1503664  1471040
부산광역시   2567910  3434423
서울특별시  10312545  9728046
인천광역시   2758296  2947217

In [78]:
korea_mdf.stack()

광주광역시  2010     1454634
       2020     1455048
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
부산광역시  2010     2567910
       2020     3434423
서울특별시  2010    10312545
       2020     9728046
인천광역시  2010     2758296
       2020     2947217
dtype: int64

In [79]:
male_tuples = [5111259, 4732275,
              1773170, 1668618,
              1390356, 1476813,
              1255245, 1198815,
              753648, 734441,
              721780, 720060]
  
male_tuple

{'광주광역시': 720060,
 '대구광역시': 1198815,
 '대전광역시': 734441,
 '부산광역시': 1668618,
 '서울특별시': 4732275,
 '인천광역시': 1476813}

In [80]:
korea_mdf = pd.DataFrame({'총인구수': population,
                          '남자인구수': male_tuples})
korea_mdf

                총인구수    남자인구수
서울특별시 2010  10312545  5111259
      2020   9728046  4732275
부산광역시 2010   2567910  1773170
      2020   3434423  1668618
인천광역시 2010   2758296  1390356
      2020   2947217  1476813
대구광역시 2010   2511676  1255245
      2020   2427954  1198815
대전광역시 2010   1503664   753648
      2020   1471040   734441
광주광역시 2010   1454634   721780
      2020   1455048   720060

In [81]:
female_tuples = [5201286, 4988571,
                 1794740, 1735805,
                 1367940, 1470404,
                 1256431, 1229139,
                 750016, 736599,
                 732856, 734988]
female_tuples

[5201286,
 4988571,
 1794740,
 1735805,
 1367940,
 1470404,
 1256431,
 1229139,
 750016,
 736599,
 732856,
 734988]

In [82]:
korea_mdf = pd.DataFrame({'총인구수': population,
                          '남자인구수': male_tuples,
                          '여자인구수': female_tuples})
korea_mdf

                총인구수    남자인구수    여자인구수
서울특별시 2010  10312545  5111259  5201286
      2020   9728046  4732275  4988571
부산광역시 2010   2567910  1773170  1794740
      2020   3434423  1668618  1735805
인천광역시 2010   2758296  1390356  1367940
      2020   2947217  1476813  1470404
대구광역시 2010   2511676  1255245  1256431
      2020   2427954  1198815  1229139
대전광역시 2010   1503664   753648   750016
      2020   1471040   734441   736599
광주광역시 2010   1454634   721780   732856
      2020   1455048   720060   734988

In [83]:
ratio = korea_mdf['남자인구수'] * 100 / korea_mdf['여자인구수']
ratio

서울특별시  2010     98.269140
       2020     94.862336
부산광역시  2010     98.798155
       2020     96.129346
인천광역시  2010    101.638668
       2020    100.435867
대구광역시  2010     99.905606
       2020     97.532907
대전광역시  2010    100.484256
       2020     99.707032
광주광역시  2010     98.488653
       2020     97.968946
dtype: float64

In [84]:
ratio.unstack()

             2010        2020
광주광역시   98.488653   97.968946
대구광역시   99.905606   97.532907
대전광역시  100.484256   99.707032
부산광역시   98.798155   96.129346
서울특별시   98.269140   94.862336
인천광역시  101.638668  100.435867

In [85]:
korea_mdf = pd.DataFrame({'총인구수': population,
                          '남자인구수': male_tuples,
                          '여자인구수': female_tuples,
                          '남여비율': ratio})
korea_mdf

                총인구수    남자인구수    여자인구수        남여비율
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9728046  4732275  4988571   94.862336
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3434423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454634   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

#### 다중 인덱스 생성

In [86]:
df = pd.DataFrame(np.random.rand(6, 3),
                 index=[['a','a','b','b','c','c'],[1,2,1,2,1,2]],
                  columns=['c1', 'c2', 'c3'])
df

           c1        c2        c3
a 1  0.904856  0.361294  0.267696
  2  0.697717  0.425833  0.389373
b 1  0.280695  0.313641  0.488147
  2  0.747409  0.630700  0.367868
c 1  0.407141  0.690470  0.911981
  2  0.546182  0.984900  0.633396

In [87]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b', 'c', 'c'], [1, 2, 1, 2, 1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [88]:
pd.MultiIndex.from_tuples([('a', 1), ('a',2), ('b', 1), ('b', 2), ('c', 1), ('c', 2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [89]:
pd.MultiIndex.from_product([['a','b','c'], [1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [90]:
pd.MultiIndex(levels = [['a', 'b', 'c'], [1, 2]],
              codes = [[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [91]:
population

서울특별시  2010    10312545
       2020     9728046
부산광역시  2010     2567910
       2020     3434423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454634
       2020     1455048
dtype: int64

In [92]:
population.index.names=['행정구역', '년도']
population

행정구역   년도
서울특별시  2010    10312545
       2020     9728046
부산광역시  2010     2567910
       2020     3434423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454634
       2020     1455048
dtype: int64

In [93]:
idx = pd.MultiIndex.from_product([['a', 'b', 'c'], [1, 2]],
                                 names=['name1', 'name2'])
cols = pd.MultiIndex.from_product([['c1', 'c2', 'c3'], [1, 2]],
                                   names = ['col_name1', 'col_names2'])
data = np.round(np.random.randn(6, 6), 2)
mdf = pd.DataFrame(data, index=idx, columns=cols)
mdf

col_name1      c1          c2          c3
col_names2      1     2     1     2     1     2
name1 name2
a     1     -0.45  0.33  1.55 -0.56  1.24  2.06
      2     -0.12  0.48  0.35  0.14 -2.31 -0.38
b     1     -0.05  0.39  0.91 -0.91  1.52 -0.36
      2      0.16 -0.27 -0.17  1.62  0.30 -0.58
c     1      0.44 -1.51  0.75  0.51  1.25 -0.71
      2     -0.50 -1.19  0.86  1.07  2.21 -1.46

In [94]:
mdf['c2']

col_names2      1     2
name1 name2
a     1      1.55 -0.56
      2      0.35  0.14
b     1      0.91 -0.91
      2     -0.17  1.62
c     1      0.75  0.51
      2      0.86  1.07

In [95]:
mdf['c2'][2]

name1  name2
a      1       -0.56
       2        0.14
b      1       -0.91
       2        1.62
c      1        0.51
       2        1.07
Name: 2, dtype: float64

#### 인덱싱 및 슬라이싱

In [96]:
population

행정구역   년도
서울특별시  2010    10312545
       2020     9728046
부산광역시  2010     2567910
       2020     3434423
인천광역시  2010     2758296
       2020     2947217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454634
       2020     1455048
dtype: int64

In [97]:
population['인천광역시', 2010]

2758296

In [98]:
population[:, 2010]

행정구역
서울특별시    10312545
부산광역시     2567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454634
dtype: int64

In [99]:
population[population > 3000000]

행정구역   년도
서울특별시  2010    10312545
       2020     9728046
부산광역시  2020     3434423
dtype: int64

In [100]:
population[['대구광역시', '대전광역시']]

행정구역   년도
대구광역시  2010    2511676
       2020    2427954
대전광역시  2010    1503664
       2020    1471040
dtype: int64

In [101]:
mdf['c2',1]

name1  name2
a      1        1.55
       2        0.35
b      1        0.91
       2       -0.17
c      1        0.75
       2        0.86
Name: (c2, 1), dtype: float64

In [102]:
mdf.loc[:, ('c2', 1)]

name1  name2
a      1        1.55
       2        0.35
b      1        0.91
       2       -0.17
c      1        0.75
       2        0.86
Name: (c2, 1), dtype: float64

In [103]:
idx_slice = pd.IndexSlice
mdf.loc[idx_slice[:, 2], idx_slice[:, 2]]

col_name1      c1    c2    c3
col_names2      2     2     2
name1 name2
a     2      0.48  0.14 -0.38
b     2     -0.27  1.62 -0.58
c     2     -1.19  1.07 -1.46

#### 다중 인덱스 재정렬

In [104]:
idx

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           names=['name1', 'name2'])

In [105]:
korea_mdf

                총인구수    남자인구수    여자인구수        남여비율
행정구역  년도
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9728046  4732275  4988571   94.862336
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3434423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454634   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

In [106]:
# korea_mdf['서울특별시':'인천광역시'] #UnsortedIndexError

korea_mdf = korea_mdf.sort_index() # 위와 비교해 보면 인덱스가 가나다 순으로 sorted 됨
korea_mdf

                총인구수    남자인구수    여자인구수        남여비율
행정구역  년도
광주광역시 2010   1454634   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3434423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9728046  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [107]:
korea_mdf['서울특별시':'인천광역시']

                총인구수    남자인구수    여자인구수        남여비율
행정구역  년도
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9728046  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [108]:
korea_mdf.unstack(level=0)

         총인구수                    ...       남여비율
행정구역    광주광역시    대구광역시    대전광역시  ...      부산광역시      서울특별시       인천광역시
년도                               ...
2010  1454634  2511676  1503664  ...  98.798155  98.269140  101.638668
2020  1455048  2427954  1471040  ...  96.129346  94.862336  100.435867

[2 rows x 24 columns]

In [109]:
korea_mdf.unstack(level=1)

           총인구수             남자인구수  ...    여자인구수        남여비율
년도         2010     2020     2010  ...     2020        2010        2020
행정구역                               ...
광주광역시   1454634  1455048   721780  ...   734988   98.488653   97.968946
대구광역시   2511676  2427954  1255245  ...  1229139   99.905606   97.532907
대전광역시   1503664  1471040   753648  ...   736599  100.484256   99.707032
부산광역시   2567910  3434423  1773170  ...  1735805   98.798155   96.129346
서울특별시  10312545  9728046  5111259  ...  4988571   98.269140   94.862336
인천광역시   2758296  2947217  1390356  ...  1470404  101.638668  100.435867

[6 rows x 8 columns]

In [110]:
korea_mdf.stack()

행정구역   년도
광주광역시  2010  총인구수     1.454634e+06
             남자인구수    7.217800e+05
             여자인구수    7.328560e+05
             남여비율     9.848865e+01
       2020  총인구수     1.455048e+06
             남자인구수    7.200600e+05
             여자인구수    7.349880e+05
             남여비율     9.796895e+01
대구광역시  2010  총인구수     2.511676e+06
             남자인구수    1.255245e+06
             여자인구수    1.256431e+06
             남여비율     9.990561e+01
       2020  총인구수     2.427954e+06
             남자인구수    1.198815e+06
             여자인구수    1.229139e+06
             남여비율     9.753291e+01
대전광역시  2010  총인구수     1.503664e+06
             남자인구수    7.536480e+05
             여자인구수    7.500160e+05
             남여비율     1.004843e+02
       2020  총인구수     1.471040e+06
             남자인구수    7.344410e+05
             여자인구수    7.365990e+05
             남여비율     9.970703e+01
부산광역시  2010  총인구수     2.567910e+06
             남자인구수    1.773170e+06
             여자인구수    1.794740e+06
             남여비율     9.879815e+01
       2020  총인구수     3.434423e+06
             남자인구수    1.668618e+06
             여자인구수    1.735805e+06
             남여비율     9.612935e+01
서울특별시  2010  총인구수     1.031254e+07
             남자인구수    5.111259e+06
             여자인구수    5.201286e+06
             남여비율     9.826914e+01
       2020  총인구수     9.728046e+06
             남자인구수    4.732275e+06
             여자인구수    4.988571e+06
             남여비율     9.486234e+01
인천광역시  2010  총인구수     2.758296e+06
             남자인구수    1.390356e+06
             여자인구수    1.367940e+06
             남여비율     1.016387e+02
       2020  총인구수     2.947217e+06
             남자인구수    1.476813e+06
             여자인구수    1.470404e+06
             남여비율     1.004359e+02
dtype: float64

In [111]:
korea_mdf

                총인구수    남자인구수    여자인구수        남여비율
행정구역  년도
광주광역시 2010   1454634   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3434423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9728046  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

In [112]:
idx_flat = korea_mdf.reset_index(level=0)
idx_flat

       행정구역      총인구수    남자인구수    여자인구수        남여비율
년도
2010  광주광역시   1454634   721780   732856   98.488653
2020  광주광역시   1455048   720060   734988   97.968946
2010  대구광역시   2511676  1255245  1256431   99.905606
2020  대구광역시   2427954  1198815  1229139   97.532907
2010  대전광역시   1503664   753648   750016  100.484256
2020  대전광역시   1471040   734441   736599   99.707032
2010  부산광역시   2567910  1773170  1794740   98.798155
2020  부산광역시   3434423  1668618  1735805   96.129346
2010  서울특별시  10312545  5111259  5201286   98.269140
2020  서울특별시   9728046  4732275  4988571   94.862336
2010  인천광역시   2758296  1390356  1367940  101.638668
2020  인천광역시   2947217  1476813  1470404  100.435867

In [113]:
idx_flat = korea_mdf.reset_index(level=(0, 1))
idx_flat

     행정구역    년도      총인구수    남자인구수    여자인구수        남여비율
0   광주광역시  2010   1454634   721780   732856   98.488653
1   광주광역시  2020   1455048   720060   734988   97.968946
2   대구광역시  2010   2511676  1255245  1256431   99.905606
3   대구광역시  2020   2427954  1198815  1229139   97.532907
4   대전광역시  2010   1503664   753648   750016  100.484256
5   대전광역시  2020   1471040   734441   736599   99.707032
6   부산광역시  2010   2567910  1773170  1794740   98.798155
7   부산광역시  2020   3434423  1668618  1735805   96.129346
8   서울특별시  2010  10312545  5111259  5201286   98.269140
9   서울특별시  2020   9728046  4732275  4988571   94.862336
10  인천광역시  2010   2758296  1390356  1367940  101.638668
11  인천광역시  2020   2947217  1476813  1470404  100.435867

In [114]:
idx_flat.set_index(['행정구역', '년도'])

                총인구수    남자인구수    여자인구수        남여비율
행정구역  년도
광주광역시 2010   1454634   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3434423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9728046  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867

## 데이터 연산

In [115]:
s = pd.Series(np.random.randint(0, 10, 5))
s

0    7
1    8
2    9
3    0
4    1
dtype: int64

In [116]:
df = pd.DataFrame(np.random.randint(0, 10, (3, 3)),
                  columns=['A', 'B', 'C'])
df

   A  B  C
0  5  0  4
1  5  6  7
2  3  0  6

In [117]:
np.exp(s)

0    1096.633158
1    2980.957987
2    8103.083928
3       1.000000
4       2.718282
dtype: float64

In [118]:
np.cos(df * np.pi/4)

          A             B             C
0 -0.707107  1.000000e+00 -1.000000e+00
1 -0.707107 -1.836970e-16  7.071068e-01
2 -0.707107  1.000000e+00 -1.836970e-16

In [119]:
s1 = pd.Series([1, 3, 5, 7, 9], index=[0, 1, 2, 3, 4])
s2 = pd.Series([2, 4, 6, 8, 10], index=[1, 2, 3, 4, 5])
s1 + s2

0     NaN
1     5.0
2     9.0
3    13.0
4    17.0
5     NaN
dtype: float64

인덱스 기준이기때문에 없다면 NaN 으로 나오게 된다.  
그래서 아래와 같이 하게 되면 null 값을 0으로 채우게 된다.

In [120]:
s1.add(s2, fill_value=0)

0     1.0
1     5.0
2     9.0
3    13.0
4    17.0
5    10.0
dtype: float64

In [121]:
df1 = pd.DataFrame(np.random.randint(0, 20, (3, 3)), 
                   columns = list('ACD'))

df1

    A   C   D
0   6  13  11
1  19   3   3
2  13  12  13

In [122]:
df2 = pd.DataFrame(np.random.randint(0, 20, (5, 5)),
                   columns = list('BAECD'))
df2

    B   A   E   C   D
0   4  13  14   6  17
1   7   2  16  11   1
2   4  12   3  15  11
3  18  14   6   0  15
4   0   8   2   6  10

In [123]:
df1 + df2

      A   B     C     D   E
0  19.0 NaN  19.0  28.0 NaN
1  21.0 NaN  14.0   4.0 NaN
2  25.0 NaN  27.0  24.0 NaN
3   NaN NaN   NaN   NaN NaN
4   NaN NaN   NaN   NaN NaN

In [124]:
fvalue = df1.stack().mean()
df1.add(df2, fill_value=fvalue)

           A          B          C          D          E
0  19.000000  14.333333  19.000000  28.000000  24.333333
1  21.000000  17.333333  14.000000   4.000000  26.333333
2  25.000000  14.333333  27.000000  24.000000  13.333333
3  24.333333  28.333333  10.333333  25.333333  16.333333
4  18.333333  10.333333  16.333333  20.333333  12.333333

### 연산자 범용 함수

#### add()

In [125]:
a = np.random.randint(1, 10, size=(3, 3))
a

array([[3, 9, 5],
       [1, 1, 4],
       [7, 4, 4]])

In [126]:
a + a[0]

array([[ 6, 18, 10],
       [ 4, 10,  9],
       [10, 13,  9]])

In [127]:
df =pd.DataFrame(a, columns=list('ABC'))
df

   A  B  C
0  3  9  5
1  1  1  4
2  7  4  4

In [128]:
df + df.iloc[0]

    A   B   C
0   6  18  10
1   4  10   9
2  10  13   9

In [129]:
df.add(df.iloc[0])

    A   B   C
0   6  18  10
1   4  10   9
2  10  13   9

#### sub() / subtract()

In [130]:
a - a[0]

array([[ 0,  0,  0],
       [-2, -8, -1],
       [ 4, -5, -1]])

In [131]:
df

   A  B  C
0  3  9  5
1  1  1  4
2  7  4  4

In [132]:
df - df.iloc[0]

   A  B  C
0  0  0  0
1 -2 -8 -1
2  4 -5 -1

In [133]:
df - df.iloc[:,0]

    A   B   C   0   1   2
0 NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN

In [134]:
df.sub(df.iloc[0])

   A  B  C
0  0  0  0
1 -2 -8 -1
2  4 -5 -1

In [135]:
df.subtract(df['B'], axis=0)

   A  B  C
0 -6  0 -4
1  0  0  3
2  3  0  0

#### mul() / multply()

In [136]:
a

array([[3, 9, 5],
       [1, 1, 4],
       [7, 4, 4]])

In [137]:
a * a[1]

array([[ 3,  9, 20],
       [ 1,  1, 16],
       [ 7,  4, 16]])

In [138]:
df

   A  B  C
0  3  9  5
1  1  1  4
2  7  4  4

In [139]:
df * df.iloc[1]

   A  B   C
0  3  9  20
1  1  1  16
2  7  4  16

In [140]:
df.mul(df.iloc[1])

   A  B   C
0  3  9  20
1  1  1  16
2  7  4  16

In [141]:
df.multiply(df.iloc[2])

    A   B   C
0  21  36  20
1   7   4  16
2  49  16  16

#### truediv() /  div() / divide() / floordiv()

In [142]:
a

array([[3, 9, 5],
       [1, 1, 4],
       [7, 4, 4]])

In [143]:
a / a[0]

array([[1.        , 1.        , 1.        ],
       [0.33333333, 0.11111111, 0.8       ],
       [2.33333333, 0.44444444, 0.8       ]])

In [144]:
df

   A  B  C
0  3  9  5
1  1  1  4
2  7  4  4

In [145]:
df / df.iloc[0]

          A         B    C
0  1.000000  1.000000  1.0
1  0.333333  0.111111  0.8
2  2.333333  0.444444  0.8

In [146]:
df.truediv(df.iloc[0])

          A         B    C
0  1.000000  1.000000  1.0
1  0.333333  0.111111  0.8
2  2.333333  0.444444  0.8

In [147]:
df.div(df.iloc[1])

     A    B     C
0  3.0  9.0  1.25
1  1.0  1.0  1.00
2  7.0  4.0  1.00

In [148]:
df.divide(df.iloc[2])

          A     B     C
0  0.428571  2.25  1.25
1  0.142857  0.25  1.00
2  1.000000  1.00  1.00

In [149]:
a // a[0]

array([[1, 1, 1],
       [0, 0, 0],
       [2, 0, 0]])

In [150]:
df.floordiv(df.iloc[0])

   A  B  C
0  1  1  1
1  0  0  0
2  2  0  0

#### mod()

In [151]:
a

array([[3, 9, 5],
       [1, 1, 4],
       [7, 4, 4]])

In [152]:
a % a[0]

array([[0, 0, 0],
       [1, 1, 4],
       [1, 4, 4]])

In [153]:
df

   A  B  C
0  3  9  5
1  1  1  4
2  7  4  4

In [154]:
df.mod(df.iloc[0])

   A  B  C
0  0  0  0
1  1  1  4
2  1  4  4

#### pow()

In [155]:
a

array([[3, 9, 5],
       [1, 1, 4],
       [7, 4, 4]])

In [156]:
a ** a[0]

array([[       27, 387420489,      3125],
       [        1,         1,      1024],
       [      343,    262144,      1024]])

In [157]:
df

   A  B  C
0  3  9  5
1  1  1  4
2  7  4  4

In [158]:
df.pow(df.iloc[0])

     A          B     C
0   27  387420489  3125
1    1          1  1024
2  343     262144  1024

In [159]:
row = df.iloc[0, ::2]
row

A    3
C    5
Name: 0, dtype: int64

In [160]:
df - row

     A   B    C
0  0.0 NaN  0.0
1 -2.0 NaN -1.0
2  4.0 NaN -1.0

### 정렬(Sort)

In [161]:
s = pd.Series(range(5), index=['A', 'D', 'B', 'C', 'E'])
s

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [162]:
s.sort_index()

A    0
B    2
C    3
D    1
E    4
dtype: int64

In [163]:
s.sort_values()

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [164]:
df = pd.DataFrame(np.random.randint(0,10, (4, 4)),
                  index=[2, 4, 1, 3],
                  columns=list('BDAC'))
df

   B  D  A  C
2  6  2  6  3
4  8  7  2  7
1  6  2  9  6
3  7  8  0  5

In [165]:
df.sort_index()

   B  D  A  C
1  6  2  9  6
2  6  2  6  3
3  7  8  0  5
4  8  7  2  7

In [166]:
df.sort_values(by='A')

   B  D  A  C
3  7  8  0  5
4  8  7  2  7
2  6  2  6  3
1  6  2  9  6

In [167]:
df.sort_values(by=['A','C'])

   B  D  A  C
3  7  8  0  5
4  8  7  2  7
2  6  2  6  3
1  6  2  9  6

In [168]:
df.sort_index(axis=1)

   A  B  C  D
2  6  6  3  2
4  2  8  7  7
1  9  6  6  2
3  0  7  5  8

### 순위(Ranking)

![image.png]()

In [169]:
s = pd.Series([-2, 4, 7, 3, 0, 7, 5, -4, 2, 6])
s

0   -2
1    4
2    7
3    3
4    0
5    7
6    5
7   -4
8    2
9    6
dtype: int64

In [170]:
s.rank()

0    2.0
1    6.0
2    9.5
3    5.0
4    3.0
5    9.5
6    7.0
7    1.0
8    4.0
9    8.0
dtype: float64

In [171]:
s.rank(method='first') # 먼저 적힌 것이 순위를 높여준다.

0     2.0
1     6.0
2     9.0
3     5.0
4     3.0
5    10.0
6     7.0
7     1.0
8     4.0
9     8.0
dtype: float64

In [172]:
s.rank(method='max')

0     2.0
1     6.0
2    10.0
3     5.0
4     3.0
5    10.0
6     7.0
7     1.0
8     4.0
9     8.0
dtype: float64

### 고성능 연산

In [173]:
nrows, ncols = 100000, 100
df1, df2, df3, df4 = (pd.DataFrame(np.random.rand(nrows, ncols)) for i in range(4))

In [174]:
%timeit df1 + df2 + df3 + df4

10 loops, best of 5: 57.2 ms per loop

In [175]:
%timeit pd.eval('df1 + df2 + df3 + df4')

10 loops, best of 5: 38.4 ms per loop

In [176]:
%timeit df1 * -df2 / (-df3 * df4)

10 loops, best of 5: 86.6 ms per loop

In [177]:
%timeit pd.eval('df1 * -df2 / (-df3 * df4)')

10 loops, best of 5: 47.3 ms per loop

In [178]:
%timeit (df1 < df2) & (df2 <= df3 ) & (df3 != df4)

10 loops, best of 5: 57.7 ms per loop

In [179]:
%timeit pd.eval('(df1 < df2) & (df2 <= df3 ) & (df3 != df4)')

10 loops, best of 5: 86.5 ms per loop

In [180]:
df = pd.DataFrame(np.random.rand(1000000, 5), columns=['A', 'B', 'C', 'D', 'E'])
df.head()

          A         B         C         D         E
0  0.263728  0.074116  0.935273  0.873989  0.249773
1  0.333677  0.880353  0.392105  0.678108  0.893011
2  0.407499  0.571522  0.064353  0.412427  0.874212
3  0.386010  0.043852  0.008442  0.281006  0.210213
4  0.542068  0.082992  0.312424  0.493531  0.494228

In [181]:
%timeit df['A'] + df['B'] / df['C'] - df['D'] * df['E']

100 loops, best of 5: 13.2 ms per loop

In [182]:
%timeit pd.eval(' df.A + df.B / df.C - df.D * df.E')

100 loops, best of 5: 7.11 ms per loop

In [183]:
df.eval('R = A + B / C - D * E', inplace=True)
df.head()

          A         B         C         D         E         R
0  0.263728  0.074116  0.935273  0.873989  0.249773  0.124674
1  0.333677  0.880353  0.392105  0.678108  0.893011  1.973315
2  0.407499  0.571522  0.064353  0.412427  0.874212  8.927946
3  0.386010  0.043852  0.008442  0.281006  0.210213  5.521599
4  0.542068  0.082992  0.312424  0.493531  0.494228  0.563790

In [184]:
col_mean = df.mean(1)
df['A'] + col_mean

0         0.683986
1         1.192105
2         2.283825
3         1.461197
4         0.956907
            ...
999995    1.029175
999996    0.821532
999997    0.668649
999998    2.129251
999999    1.654980
Length: 1000000, dtype: float64

In [185]:
df.eval(' A + @col_mean')

0         0.683986
1         1.192105
2         2.283825
3         1.461197
4         0.956907
            ...
999995    1.029175
999996    0.821532
999997    0.668649
999998    2.129251
999999    1.654980
Length: 1000000, dtype: float64

In [186]:
df[(df.A < 0.5) & (df.B < 0.5) & (df.C > 0.5)]

               A         B         C         D         E         R
0       0.263728  0.074116  0.935273  0.873989  0.249773  0.124674
5       0.387438  0.307937  0.612639  0.422345  0.487528  0.684174
7       0.486428  0.147894  0.795291  0.378012  0.727633  0.397336
8       0.395999  0.211815  0.553642  0.256783  0.047302  0.766438
9       0.384995  0.083519  0.524655  0.974785  0.321982  0.230320
...          ...       ...       ...       ...       ...       ...
999934  0.321950  0.234547  0.797169  0.149392  0.265865  0.576457
999957  0.106831  0.392064  0.616197  0.075811  0.078212  0.737166
999963  0.489464  0.223415  0.814865  0.316659  0.401875  0.636381
999990  0.210952  0.469173  0.564875  0.575613  0.713618  0.630763
999997  0.312084  0.057303  0.815074  0.395202  0.293226  0.266504

[124728 rows x 6 columns]

In [187]:
pd.eval('df[(df.A < 0.5) & (df.B < 0.5) & (df.C > 0.5)]')

               A         B         C         D         E         R
0       0.263728  0.074116  0.935273  0.873989  0.249773  0.124674
5       0.387438  0.307937  0.612639  0.422345  0.487528  0.684174
7       0.486428  0.147894  0.795291  0.378012  0.727633  0.397336
8       0.395999  0.211815  0.553642  0.256783  0.047302  0.766438
9       0.384995  0.083519  0.524655  0.974785  0.321982  0.230320
...          ...       ...       ...       ...       ...       ...
999934  0.321950  0.234547  0.797169  0.149392  0.265865  0.576457
999957  0.106831  0.392064  0.616197  0.075811  0.078212  0.737166
999963  0.489464  0.223415  0.814865  0.316659  0.401875  0.636381
999990  0.210952  0.469173  0.564875  0.575613  0.713618  0.630763
999997  0.312084  0.057303  0.815074  0.395202  0.293226  0.266504

[124728 rows x 6 columns]

In [188]:
df.query('(A < 0.5) and (B < 0.5) and (C > 0.5)')

               A         B         C         D         E         R
0       0.263728  0.074116  0.935273  0.873989  0.249773  0.124674
5       0.387438  0.307937  0.612639  0.422345  0.487528  0.684174
7       0.486428  0.147894  0.795291  0.378012  0.727633  0.397336
8       0.395999  0.211815  0.553642  0.256783  0.047302  0.766438
9       0.384995  0.083519  0.524655  0.974785  0.321982  0.230320
...          ...       ...       ...       ...       ...       ...
999934  0.321950  0.234547  0.797169  0.149392  0.265865  0.576457
999957  0.106831  0.392064  0.616197  0.075811  0.078212  0.737166
999963  0.489464  0.223415  0.814865  0.316659  0.401875  0.636381
999990  0.210952  0.469173  0.564875  0.575613  0.713618  0.630763
999997  0.312084  0.057303  0.815074  0.395202  0.293226  0.266504

[124728 rows x 6 columns]

In [189]:
col_mean = df['D'].mean()
df[(df.A < col_mean) & (df.B < col_mean)]

               A         B         C         D         E         R
0       0.263728  0.074116  0.935273  0.873989  0.249773  0.124674
3       0.386010  0.043852  0.008442  0.281006  0.210213  5.521599
5       0.387438  0.307937  0.612639  0.422345  0.487528  0.684174
6       0.109104  0.051584  0.290985  0.290428  0.215515  0.223788
7       0.486428  0.147894  0.795291  0.378012  0.727633  0.397336
...          ...       ...       ...       ...       ...       ...
999986  0.015016  0.448794  0.411474  0.514640  0.149652  1.028697
999990  0.210952  0.469173  0.564875  0.575613  0.713618  0.630763
999991  0.246081  0.110481  0.098546  0.764230  0.192273  1.220254
999992  0.123033  0.258327  0.240943  0.180223  0.201138  1.158932
999997  0.312084  0.057303  0.815074  0.395202  0.293226  0.266504

[249596 rows x 6 columns]

In [190]:
df.query(' A < @col_mean and B < @col_mean')

               A         B         C         D         E         R
0       0.263728  0.074116  0.935273  0.873989  0.249773  0.124674
3       0.386010  0.043852  0.008442  0.281006  0.210213  5.521599
5       0.387438  0.307937  0.612639  0.422345  0.487528  0.684174
6       0.109104  0.051584  0.290985  0.290428  0.215515  0.223788
7       0.486428  0.147894  0.795291  0.378012  0.727633  0.397336
...          ...       ...       ...       ...       ...       ...
999986  0.015016  0.448794  0.411474  0.514640  0.149652  1.028697
999990  0.210952  0.469173  0.564875  0.575613  0.713618  0.630763
999991  0.246081  0.110481  0.098546  0.764230  0.192273  1.220254
999992  0.123033  0.258327  0.240943  0.180223  0.201138  1.158932
999997  0.312084  0.057303  0.815074  0.395202  0.293226  0.266504

[249596 rows x 6 columns]

## 데이터 결합

### Concat() / Append()

In [194]:
s1 = pd.Series(['a', 'b'], index=[1, 2])
s2 = pd.Series(['c', 'd'], index=[3, 4])
pd.concat([s1,s2])

1    a
2    b
3    c
4    d
dtype: object

In [197]:
def create_df(cols, idx):
  data = {c: [str(c.lower()) + str(i) for i in idx] for c in cols}
  return pd.DataFrame(data, idx)

In [198]:
df1 = create_df('AB', [1, 2])
df1

    A   B
1  a1  b1
2  a2  b2

In [199]:
df2 = create_df('AB', [3, 4])
df2

    A   B
3  a3  b3
4  a4  b4

In [200]:
pd.concat([df1, df2])

    A   B
1  a1  b1
2  a2  b2
3  a3  b3
4  a4  b4

In [201]:
df3 = create_df('AB', [0, 1])
df3

    A   B
0  a0  b0
1  a1  b1

In [203]:
df4 = create_df('CD', [0, 1])
df4

    C   D
0  c0  d0
1  c1  d1

In [204]:
pd.concat([df3, df4])

     A    B    C    D
0   a0   b0  NaN  NaN
1   a1   b1  NaN  NaN
0  NaN  NaN   c0   d0
1  NaN  NaN   c1   d1

In [205]:
# pd.concat([df1, df3], verify_integrity=True) # 결합하면 안되?! 확인

ValueError: ignored

In [206]:
pd.concat([df1, df3], ignore_index=True)

    A   B
0  a1  b1
1  a2  b2
2  a0  b0
3  a1  b1

In [207]:
pd.concat([df1, df3], keys=['X', 'Y'])

      A   B
X 1  a1  b1
  2  a2  b2
Y 0  a0  b0
  1  a1  b1

In [208]:
df5 = create_df('ABC', [1, 2])
df6 = create_df('BCD', [3, 4])
pd.concat([df5, df6])

     A   B   C    D
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b3  c3   d3
4  NaN  b4  c4   d4

In [209]:
pd.concat([df5, df6], join='inner')

    B   C
1  b1  c1
2  b2  c2
3  b3  c3
4  b4  c4

In [210]:
df5.append(df6)

     A   B   C    D
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b3  c3   d3
4  NaN  b4  c4   d4

In [211]:
pd.concat([df3, df4], axis=1)

    A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1

In [212]:
pd.concat([df1, df2])

    A   B
1  a1  b1
2  a2  b2
3  a3  b3
4  a4  b4

### 병합과 조인

In [215]:
df1 = pd.DataFrame({'학생': ['홍길동', '이순신', '임꺽정', '김유식'],
                    '학과': ['경영학과', '교육학과', '컴퓨터학과','통계학과']})
df1

    학생     학과
0  홍길동   경영학과
1  이순신   교육학과
2  임꺽정  컴퓨터학과
3  김유식   통계학과

In [217]:
df2 = pd.DataFrame({'학생': ['홍길동', '이순신', '임꺽정', '김유식'],
                    '입학년도': [2012, 2016, 2019, 2020]})
df2

    학생  입학년도
0  홍길동  2012
1  이순신  2016
2  임꺽정  2019
3  김유식  2020

In [218]:
df3 = pd.merge(df1, df2)
df3

    학생     학과  입학년도
0  홍길동   경영학과  2012
1  이순신   교육학과  2016
2  임꺽정  컴퓨터학과  2019
3  김유식   통계학과  2020

In [219]:
df4 = pd.DataFrame({'학과': ['경영학과', '교육학과', '컴퓨터학과', '통계학과'],
                    '학과장':['황희', '장영실', '안창호', '정약용']})
df4

      학과  학과장
0   경영학과   황희
1   교육학과  장영실
2  컴퓨터학과  안창호
3   통계학과  정약용

In [220]:
pd.merge(df3, df4)

    학생     학과  입학년도  학과장
0  홍길동   경영학과  2012   황희
1  이순신   교육학과  2016  장영실
2  임꺽정  컴퓨터학과  2019  안창호
3  김유식   통계학과  2020  정약용

In [222]:
df5 = pd.DataFrame({'학과': ['경영학과', '교육학과', '교육학과','컴퓨터학과','컴퓨터학과','통계학과'],
                    '과목': ['경영개론', '기초수학', '물리학','프로그래밍','운영체제','확률론']})
df5

      학과     과목
0   경영학과   경영개론
1   교육학과   기초수학
2   교육학과    물리학
3  컴퓨터학과  프로그래밍
4  컴퓨터학과   운영체제
5   통계학과    확률론

In [224]:
pd.merge(df1, df5) # 학과 기준 ! 왜? 학과가 기준이니까

    학생     학과     과목
0  홍길동   경영학과   경영개론
1  이순신   교육학과   기초수학
2  이순신   교육학과    물리학
3  임꺽정  컴퓨터학과  프로그래밍
4  임꺽정  컴퓨터학과   운영체제
5  김유식   통계학과    확률론

In [225]:
pd.merge(df1, df2, on='학생')

    학생     학과  입학년도
0  홍길동   경영학과  2012
1  이순신   교육학과  2016
2  임꺽정  컴퓨터학과  2019
3  김유식   통계학과  2020

In [226]:
df6 = pd.DataFrame({'이름': ['홍길동', '이순신', '임꺽정', '김유신'],
                    '성적': ['A', 'A+', 'B', 'A+']})
df6

    이름  성적
0  홍길동   A
1  이순신  A+
2  임꺽정   B
3  김유신  A+

## 데이터 집계와 그룹 연산

#### 집계 연산(Aggregation)

### GroupBy 연산

### 피벗 테이블(Pivot Table)

### 범주형(Categorical) 데이터

## 문자열 연산

#### 문자열 연산자

#### 기타 연산자

#### 정규표현식

## 시계열 처리

#### 시계열 데이터 구조

### 시계열 기본

### 주기와 오프셋

### 시프트(Shift)

### 시간대 처리

* 국제표준시(Coordinated Universal Time, UTC)를 기준으로 떨어진 거리만큼 오프셋으로 시간대 처리
* 전 세계의 시간대 정보를 모아놓은 올슨 데이터베이스를 활용한 라이브러리인 `pytz` 사용

### 기간과 기간 연산

### 리샘플링(Resampling)

* 리샘플링(Resampling): 시계열의 빈도 변환
* 다운샘플링(Down sampling): 상위 빈도 데이터를 하위 빈도 데이터로 집계
* 업샘플링(Up sampling): 하위 빈도 데이터를 상위 빈도 데이터로 집계

### 무빙 윈도우(Moving Window)

## 데이터 읽기 및 저장

### 텍스트 파일 읽기/쓰기

### 이진 데이터 파일 읽기/쓰기

## 데이터 정제

### 누락값 처리

* 대부분의 실제 데이터들은 정제되지 않고 누락값들이 존재
* 서로 다른 데이터들은 다른 형태의 결측을 가짐
* 결측 데이터는 `null`, `NaN`, `NA`로 표기

#### None: 파이썬 누락 데이터

#### NaN: 누락된 수치 데이터

#### Null 값 처리

### 중복 제거

### 값 치환

## 참고문헌

* Pandas 사이트: https://pandas.pydata.org/
* Jake VanderPlas, "Python Data Science Handbook", O'Reilly
* Wes Mckinney, "Python for Data Analysis", O'Reilly